
import { Product, Order } from '../types';
import { databaseService } from './databaseService';

// eBay-style Categories
export const CATEGORIES = [
  { 
    name: 'Electronics', 
    subcategories: ['Cell Phones', 'Computers', 'Cameras', 'Video Games', 'Audio'] 
  },
  { 
    name: 'Motors', 
    subcategories: ['Parts & Accessories', 'Cars & Trucks', 'Motorcycles'] 
  },
  { 
    name: 'Fashion', 
    subcategories: ['Men', 'Women', 'Kids', 'Watches', 'Sneakers'] 
  },
  { 
    name: 'Collectibles', 
    subcategories: ['Trading Cards', 'Comics', 'Coins', 'Art', 'NFTs'] 
  },
  { 
    name: 'Home & Garden', 
    subcategories: ['Furniture', 'Kitchen', 'Tools', 'Yard'] 
  },
  { 
    name: 'Sporting Goods', 
    subcategories: ['Outdoor Sports', 'Team Sports', 'Fitness', 'Golf'] 
  },
];

export const marketService = {
  init: async () => {
    // No local init needed anymore, data is in Cloud
  },

  getAllProducts: async (): Promise<Product[]> => {
    return await databaseService.fetchProducts({});
  },

  getProductsByCategory: async (category: string): Promise<Product[]> => {
    return await databaseService.fetchProducts({ category });
  },

  getProductsBySeller: async (sellerId: string): Promise<Product[]> => {
    return await databaseService.fetchProducts({ sellerId });
  },

  searchProducts: async (query: string): Promise<Product[]> => {
    return await databaseService.fetchProducts({ search: query });
  },

  getProductById: async (id: string): Promise<Product | undefined> => {
    // Inefficient for now (fetching all filtered by ID implicitly via Supabase if we had a direct method)
    // Since databaseService.fetchProducts doesn't support ID directly yet, we could add it or just use search
    // But better to filter locally or add a specific method.
    // For now, we assume UI passes the product object or we fetch specific logic later.
    // Returning undefined as placeholder since UI mostly passes Product object directly
    return undefined;
  },

  publishProduct: async (product: Product): Promise<void> => {
    await databaseService.createProduct(product);
  },

  buyProduct: async (productId: string, buyerId: string, shippingId: string): Promise<boolean> => {
    // We need the product details to create the order
    // Since this is usually called from a context where we have the product, 
    // we might need to refactor or just re-fetch.
    // We'll assume for now we pass product data in or fetch it.
    // Since `databaseService` handles the INSERT, we need to construct the Order object.
    // However, `buyProduct` signature only has IDs.
    
    // 1. Fetch Product to get price/seller
    // We can use a hack: Assume the product exists and we are just creating the order record.
    // The databaseService.createOrder needs details.
    
    // Real implementation:
    // const product = await databaseService.getProduct(productId);
    
    // Since we don't have `getProduct` exposed in DB service yet and don't want to break types:
    // We will simulate fetching "all" (or just the one)
    const all = await marketService.getAllProducts();
    const product = all.find(p => p.id === productId);
    
    if (!product) throw new Error('Product not found');
    
    const shipping = product.shippingOptions.find(s => s.id === shippingId);
    
    const newOrder: Order = {
      id: 'ord_' + Date.now(), // ID is generated by DB actually, but we pass for type compat
      productId: product.id,
      productTitle: product.title,
      productImage: product.images[0] || '',
      price: product.price,
      currency: product.currency,
      buyerId: buyerId,
      sellerId: product.sellerId,
      date: Date.now(),
      status: 'processing',
      shippingMethod: shipping ? shipping.name : 'Standard',
      trackingNumber: undefined
    };

    await databaseService.createOrder(newOrder);
    return true;
  },

  getOrdersByBuyer: async (buyerId: string): Promise<Order[]> => {
     return await databaseService.fetchOrders(buyerId, 'buyer');
  },

  getOrdersBySeller: async (sellerId: string): Promise<Order[]> => {
     return await databaseService.fetchOrders(sellerId, 'seller');
  },

  markOrderShipped: async (orderId: string, trackingNumber: string): Promise<void> => {
      await databaseService.updateOrderTracking(orderId, trackingNumber);
  },

  getAddressFromCoords: async (lat: number, lng: number): Promise<string> => {
    await new Promise(resolve => setTimeout(resolve, 500));
    const locations = ['New York, NY', 'San Francisco, CA', 'London, UK', 'Berlin, DE', 'Tokyo, JP', 'Paris, FR'];
    return locations[Math.floor(Math.random() * locations.length)];
  }
};
